# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\dasishnag\shijian\实验：恶意DGA域名检测系统的简单实现\DGADetection\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow,knn,svm):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(320, 87)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(30, 10, 271, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(120, 40, 75, 23))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.pushButton.clicked.connect(lambda:self.clfpre(self.lineEdit.text()))
        self.KNN = knn
        self.SVM = svm
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "恶意域名检测系统"))
        self.pushButton.setText(_translate("MainWindow", "开始检测"))
    
    def showjieguo(self,jieguo):
        from Ui_jieguo import Ui_dialog
        self.form = QtWidgets.QWidget()
        self.ui = Ui_dialog()
        self.ui.setupUi(self.form)
        from PyQt5.QtCore import Qt
        self.ui.pushButton.clicked.connect(self.form.close)
        for i in range(self.ui.tableWidget.rowCount()):
            for j in range(self.ui.tableWidget.columnCount()):
                s = str(jieguo[i][j])
                if(i==1):s = str(jieguo[i][j] * 100)[:5] + '%'
                self.ui.tableWidget.setItem(i, j, QtWidgets.QTableWidgetItem(s))
                self.ui.tableWidget.item(i,j).setTextAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.form.setWindowModality(Qt.ApplicationModal)
        self.form.show()
        return 
    


    def clfpre(self,url):
        print(url)
        from urltest import isValidURL
        if(isValidURL(url)):
            # jieguo = []
            label1,pro1 = self.KNN.predict_single_dname(r"./data/model",url)
            label2,pro2 = self.SVM.predict_single_dname(r"./data/model",url)

            self.showjieguo([[label1,label2],[pro1,pro2]])
        else:
            QtWidgets.QMessageBox.critical(QtWidgets.QWidget() ,"URL填写错误", "请仔细检查是否输入了格式正确的URL")
        return 0

