# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pin.xdc

# IP: ip/bin2bcd_0/bin2bcd_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bin2bcd_0 || ORIG_REF_NAME==bin2bcd_0} -quiet] -quiet
